### ISSUE TITLE
README no longer correct

### ISSUE THREAD

**Issue by chiffon-rouge** [Numkil/VimConf#4]
I just want to inform you that your instructions are no longer correct regarding:

>Running vim with this .vimrc will cause it to automatically install Vundle and a bunch of plugins. (I hope)

Running vim fresh using your vimrc will only automatically install NeoBundle but not the plugins defined in your rc (which wasn't always the case). This must be done manually in vim by invoking the respective NeoBundle commands. It's no big deal and not really an issue but I guess you might want to know this and maybe change that part in your readme.

**Comment by Numkil** [comment]
Looks like Shougo changed how neobundlecheck works. Now you don't have a friendly prompt anymore, but he will automatically install the bundles. Thanks for giving me a  heads up!
